[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "solmate=lib/solmate/src",
    "forge-std/=lib/forge-std/src/",                                # Explicitly add forge-std for clarity
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
